/**
 * @author rhdes
 * ROLE
 * CDU
 * ACAO
 */
export const securityRoles = {
    /**
     * Role Admin
     */
    ROLE_ADMIN_ADMIN: "ROLE_ADMIN_ADMIN",

    /**
     * Role Cliente
     */
    ROLE_CLIENTE: "ROLE_CLIENTE",
    ROLE_CLIENTE_NEW: "ROLE_CLIENTE_NEW",
    ROLE_CLIENTE_EDIT: "ROLE_CLIENTE_EDIT",
    ROLE_CLIENTE_DISABLED: "ROLE_CLIENTE_DISABLED",
    ROLE_CLIENTE_DELETE: "ROLE_CLIENTE_DELETE",

    /**
     * Role Fornecedores
     */
    ROLE_FORNECEDOR: "ROLE_FORNECEDOR",
    ROLE_FORNECEDOR_NEW: "ROLE_FORNECEDOR_NEW",
    ROLE_FORNECEDOR_EDIT: "ROLE_FORNECEDOR_EDIT",
    ROLE_FORNECEDOR_DISABLED: "ROLE_FORNECEDOR_DISABLED",
    ROLE_FORNECEDOR_DELETE: "ROLE_FORNECEDOR_DELETE",

    /**
     * Role Estoque
     */
    ROLE_ESTOQUE: "ROLE_ESTOQUE",
    ROLE_ESTOQUE_NEW: "ROLE_ESTOQUE_NEW",
    ROLE_ESTOQUE_EDIT: "ROLE_ESTOQUE_EDIT",
    ROLE_ESTOQUE_DELETE: "ROLE_ESTOQUE_DELETE",

    /**
     * Roles Nota Fiscal
     */
    ROLE_NOTAFISCAL: "ROLE_NOTAFISCAL",
    ROLE_NOTAFISCAL_NEW: "ROLE_NOTAFISCAL_NEW",
    ROLE_NOTAFISCAL_EDIT: "ROLE_NOTAFISCAL_EDIT",
    ROLE_NOTAFISCAL_DELETE: "ROLE_NOTAFISCAL_DELETE",

    /**
     * Roles Produto
     */
    ROLE_PRODUTO: "ROLE_PRODUTO",
    ROLE_PRODUTO_NEW: "ROLE_PRODUTO_NEW",
    ROLE_PRODUTO_EDIT: "ROLE_PRODUTO_EDIT",
    ROLE_PRODUTO_DELETE: "ROLE_PRODUTO_DELETE",
    ROLE_PRODUTO_DISABLED: "ROLE_PRODUTO_DISABLED",

    /**
     * Roles Tipo Produto
     */
    ROLE_TIPOPRODUTO: "ROLE_TIPOPRODUTO",
    ROLE_TIPOPRODUTO_NEW: "ROLE_TIPOPRODUTO_NEW",
    ROLE_TIPOPRODUTO_EDIT: "ROLE_TIPOPRODUTO_EDIT",
    ROLE_TIPOPRODUTO_DELETE: "ROLE_TIPOPRODUTO_DELETE",

    /**
     * Roles NCM
     */
    ROLE_NCM: "ROLE_NCM",
    ROLE_NCM_NEW: "ROLE_NCM_UPLOAD",

    /**
     * Roles Precificação
     */
    ROLE_PRECIFICACAO: "ROLE_PRECIFICACAO",
    ROLE_PRECIFICACAO_NEW: "ROLE_PRECIFICACAO_NEW",
    ROLE_PRECIFICACAO_EDIT: "ROLE_PRECIFICACAO_EDIT",
    ROLE_PRECIFICACAO_DELETE: "ROLE_PRECIFICACAO_DELETE",
    ROLE_PRECIFICACAO_HISTORICO: "ROLE_PRECIFICACAO_HISTORICO",

    /**
     * Roles Vendas
     */
    ROLE_VENDA: "ROLE_VENDA",
    ROLE_VENDA_NEW: "ROLE_VENDA_NEW",
    ROLE_VENDA_CANCEL: "ROLE_VENDA_CANCEL",
    ROLE_VENDA_SEND: "ROLE_VENDA_SEND",
}

